baseurl: "https://www.rdegges.com/"
languageCode: "en-us"
title: "Randall Degges"
params:
  author: "Randall Degges"
  copyrightStart: "2009"
  copyrightStop: "2015"
  description: "The personal website of Randall Degges: programmer, speaker, author and entrepreneur."
  email: "r@rdegges.com"
  subtitle: "Random thoughts of a happy programmer."
  mailchimpFormAction: "http://rdegges.us5.list-manage.com/subscribe/post?u=ac8a69447e872cf6ddf171977&amp;id=62ec9e2b1c"
  googleAnalyticsTrackingId: "UA-11364428-13"
  navLinks:
    - title: "Twitter"
      url: "https://twitter.com/rdegges"
    - title: "Facebook"
      url: "https://www.facebook.com/rdegges"
    - title: "Google+"
      url: "https://plus.google.com/109157194342162880262"
    - title: "Github"
      url: "https://github.com/rdegges"
    - title: "Talks"
      url: "https://speakerdeck.com/rdegges"
    - title: "Email"
      url: "mailto:r@rdegges.com"
